# Auto-generated by learn_strategy.py.
# Copy this block into main.py between the LEARNED_PARAMS markers.

# <<LEARNED_PARAMS_START>>
LEARNED_PARAMS = {
    "prod_weight": 15.0,
    "ship_cost_weight": 1.0,
    "dist_weight": 0.15,
    "early_end_turn": 99,
    "late_start_turn": 349,
    "defend_threshold": 13,
    "min_hold_base": 1,
    "min_hold_threat": 6,
    "attack_buffer_ratio": 0.25,
    "min_attack_avail": 4,
    "min_expand_avail": 2,
    "consolidate_avail": 193,
    "consolidate_frac": 0.5,
    "aggressive_ship_ratio": 3.58,
    "defensive_ship_ratio": 0.88,
    "prod_target_early": 1.56,
}
# <<LEARNED_PARAMS_END>>
